v2:
  metadata:
    title: "SDF"
  login:
    host: "sdf-login01.slac.stanford.edu"
  job:
    adapter: "slurm"
    conf: "/run/slurm/conf/slurm.conf"
    bin_overrides:
      sbatch: "/opt/slurm/bin/sbatch"
      squeue: "/opt/slurm/bin/squeue"
      scontrol: "/opt/slurm/bin/scontrol"
      scancel: "/opt/slurm/bin/scancel"
  batch_connect:
    basic:
      script_wrapper: |
        source /etc/profile.d/modules.sh
        export MODULEPATH=/usr/share/Modules/modulefiles:/sdf/sw/modulefiles:/sdf/group/cryoem/sw/modulefiles/
        export XDG_RUNTIME_DIR=$(mktemp -d)
        module purge
        %s
      set_host: "host=$(hostname -s)"
    vnc:
      script_wrapper: |
        export WEBSOCKIFY_CMD="websockify"
        export XDG_RUNTIME_DIR=$(mktemp -d)

        # start the container instance
        export SINGULARITY_IMAGE=${SINGULARITY_IMAGE:-/sdf/sw/images/xfce/ubuntu18.04/xfce@ubuntu18.04.sif}
        export SINGULARITY_INSTANCE=$(basename -- $XDG_RUNTIME_DIR) 

        # start container
        echo "Starting image ${SINGULARITY_IMAGE} as ${SINGULARITY_INSTANCE}..."
        singularity instance start -B /sdf,/gpfs,/scratch,/lscratch --nv ${SINGULARITY_IMAGE} ${SINGULARITY_INSTANCE}

        # alias doesn't work for some reason...
        function kill(){ singularity exec instance://${SINGULARITY_INSTANCE} kill $@; }
        export -f kill
        function pkill(){ singularity exec instance://${SINGULARITY_INSTANCE} pkill $@; }
        export -f pkill
        function pgrep(){ singularity exec instance://${SINGULARITY_INSTANCE} pgrep $@; }
        export -f pgrep
        function vncserver(){ singularity exec instance://${SINGULARITY_INSTANCE} vncserver $@; }
        export -f vncserver
        function vncpasswd(){ singularity exec instance://${SINGULARITY_INSTANCE} vncpasswd $@; }
        export -f vncpasswd

        function xfconf-query(){ singularity exec instance://${SINGULARITY_INSTANCE} xfconf-query $@; }
        export -f xfconf-query
        function xfce4-session(){ singularity exec instance://${SINGULARITY_INSTANCE} xfce4-session $@; }
        export -f xfce4-session

        function gsettings(){ singularity exec instance://${SINGULARITY_INSTANCE} gsettings $@; }
        export -f gsettings
        function dconf(){ singularity exec instance://${SINGULARITY_INSTANCE} dconf $@; }
        export -f dconf
        function mate-session(){ singularity exec instance://${SINGULARITY_INSTANCE} mate-session $@; }
        export -f mate-session

        function websockify(){ singularity exec instance://${SINGULARITY_INSTANCE} websockify $@; }
        export -f websockify

        %s
      set_host: "host=$(hostname -s)"
    desktop:
      script_wrapper: |

        echo "DESKTOP VNC"

        export WEBSOCKIFY_CMD="websockify"
        export XDG_RUNTIME_DIR=$(mktemp -d)

        # start the container instance
        export SINGULARITY_IMAGE=/afs/slac/package/singularity/images/xfce/ubuntu18.04/xfce@ubuntu18.04.sif
        export SINGULARITY_INSTANCE=$(basename -- $XDG_RUNTIME_DIR)
        singularity instance start -B /gpfs,/nfs,/afs,/scratch --nv ${SINGULARITY_IMAGE} ${SINGULARITY_INSTANCE}

        # alias doesn't work for some reason...
        function kill(){ singularity exec instance://${SINGULARITY_INSTANCE} kill $@; }
        export -f kill
        function pkill(){ singularity exec instance://${SINGULARITY_INSTANCE} pkill $@; }
        export -f pkill
        function pgrep(){ singularity exec instance://${SINGULARITY_INSTANCE} pgrep $@; }
        export -f pgrep
        function vncserver(){ singularity exec instance://${SINGULARITY_INSTANCE} vncserver $@; }
        export -f vncserver
        function vncpasswd(){ singularity exec instance://${SINGULARITY_INSTANCE} vncpasswd $@; }
        export -f vncpasswd

        function xfconf-query(){ singularity exec instance://${SINGULARITY_INSTANCE} xfconf-query $@; }
        export -f xfconf-query
        function xfce4-session(){ singularity exec instance://${SINGULARITY_INSTANCE} xfce4-session $@; }
        export -f xfce4-session

        function gsettings(){ singularity exec instance://${SINGULARITY_INSTANCE} gsettings $@; }
        export -f gsettings
        function dconf(){ singularity exec instance://${SINGULARITY_INSTANCE} dconf $@; }
        export -f dconf
        function mate-session(){ singularity exec instance://${SINGULARITY_INSTANCE} mate-session $@; }
        export -f mate-session

        function websockify(){ singularity exec instance://${SINGULARITY_INSTANCE} websockify $@; }
        export -f websockify

        %s
      set_host: "host=$(hostname -s)"

