apiVersion: apps/v1
kind: Deployment
metadata:
  name: ondemand
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ondemand
  template:
    metadata:
      labels:
        app: ondemand
    spec:
      containers:
      - name: ondemand
        image: slaclab/slac-ondemand:20200417.0
        imagePullPolicy: Always
        #livenessProbe:
        #  httpGet:
        #    path: /
        #    port: 443
        #  initialDelaySeconds: 5
        #  periodSeconds: 10
        env:
        - name: OOD_SERVERNAME
          value: ondemand-dev.slac.stanford.edu
        - name: OOD_DEFAULT_SSHHOST
          value: centos7.slac.stanford.edu
        - name: OOD_AUTH_METHOD
          value: htpasswd
          #value: ldap
        #- name: OOD_AUTH_LDAPURL
        #  value: ldaps://ldap601.slac.stanford.edu:636/ou=Accounts,dc=slac,dc=stanford,dc=edu 
        volumeMounts:
        - name: slurm-config
          mountPath: /run/slurm/conf/
          readOnly: true
        - name: munge-socket
          mountPath: /var/run/munge/
        #- name: munge-key
        #  mountPath: "/mnt/munge"
        #  readOnly: true
        - name: ood-portal-config
          mountPath: /etc/ood/config/portal/
          readOnly: true
        - name: ood-clusterd-config
          mountPath: /etc/ood/config/clusters.d/
          readOnly: true
        #- name: ood-htpasswd
        #  mountPath: /etc/ood/config/htpasswd/
        #  readOnly: true
        - name: ood-certs
          mountPath: /etc/pki/tls/thisserver/
          readOnly: true
      volumes:
      #- name: slurm-config
      #  configMap:
      #    name: slurm
      #    items:
      #    - key: slurm.conf
      #      path: slurm.conf
      #- name: munge-key
      #  secret:
      #    secretName: munge
      #    defaultMode: 256
      - name: ood-portal-config
        configMap:
          name: ood-config
          items:
          - key: ood_portal.yml
            path: ood_portal.yml
      #- name: ood-clusterd-config
      #  configMap:
      #    name: ood-config
      #    items:
      #    - key: sdf_cluster.yml
      #      path: sdf.yml
      #- name: ood-htpasswd
      #  secret:
      #    secretName: auth
      #    defaultMode: 256
      #    items:
      #    - key: htpasswd
      #      path: .htpasswd
      - name: ood-certs
        secret:
          secretName: certs
          defaultMode: 420
