apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ondemand
spec:
  rules:
  - host: sdf.slac.stanford.edu
    http:
      paths:
      - backend:
          serviceName: ondemand
          servicePort: 443
        path: /
